# Generated by Django 2.0.dev20170308171458 on 2017-04-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(max_length=250)),
                ('full_address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('review_count', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('longitude', models.FloatField(default=0)),
                ('lattitude', models.FloatField(default=0)),
                ('caters', models.BooleanField(default=True)),
                ('Noise_level', models.CharField(max_length=100)),
                ('Take_Reservations', models.BooleanField()),
                ('Delivery', models.CharField(max_length=100)),
                ('Has_TV', models.BooleanField()),
                ('Outdoor_Seating', models.BooleanField()),
                ('Attire', models.CharField(max_length=100)),
                ('Alcohol', models.CharField(max_length=100)),
                ('Water_service', models.BooleanField()),
                ('Accepts_Credit_card', models.BooleanField()),
                ('good_for_kids', models.BooleanField()),
                ('good_for_groups', models.BooleanField()),
                ('price_range', models.IntegerField()),
                ('Type', models.CharField(max_length=100)),
            ],
        ),
    ]
